if (NOT DEFINED TEST_ROOT)
    set(TEST_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../tmp/find-pcap-test")
endif ()
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}/include" "${TEST_ROOT}/lib")
file(WRITE "${TEST_ROOT}/include/pcap.h" "/* fake pcap header */\n")
file(WRITE "${TEST_ROOT}/lib/libpcap.a" "")

list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

function(clear_pcap_cache)
    unset(PCAP_FOUND CACHE)
    unset(PCAP_INCLUDE_DIR CACHE)
    unset(PCAP_LIBRARY CACHE)
    unset(PCAP_LIBRARIES)
    unset(PCAP_INCLUDE_DIRS)
endfunction()

clear_pcap_cache()
set(PCAP_INCLUDE_DIR "${TEST_ROOT}/include" CACHE PATH "" FORCE)
set(PCAP_LIBRARY "PCAP_LIBRARY-NOTFOUND" CACHE FILEPATH "" FORCE)
include(FindPCAP)
if (PCAP_FOUND)
    message(FATAL_ERROR "FindPCAP accepted headers without a pcap library")
endif ()

clear_pcap_cache()
set(PCAP_INCLUDE_DIR "${TEST_ROOT}/include" CACHE PATH "" FORCE)
set(PCAP_LIBRARY "${TEST_ROOT}/lib/libpcap.a" CACHE FILEPATH "" FORCE)
include(FindPCAP)
if (NOT PCAP_FOUND)
    message(FATAL_ERROR "FindPCAP rejected headers with a pcap library")
endif ()
if (NOT "${PCAP_LIBRARIES}" STREQUAL "${TEST_ROOT}/lib/libpcap.a")
    message(FATAL_ERROR "FindPCAP did not expose the pcap library path")
endif ()

message(STATUS "find-pcap-test passed")
